name: able_us
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/Icons/Care House.png
    - Assets/Icons/Education.png
    - Assets/Icons/General Supplies.png
    - Assets/Icons/In-Home Care.png
    - Assets/Icons/Medical Services.png
    - Assets/Icons/Medical Supplies.png
    - Assets/Icons/Medicin Timer.png
    - Assets/Icons/Therapy.png
    - Assets/Icons/Work.png
    
    - Assets/Images/test.png
